name: Check

on:
  push:
  pull_request:

jobs:
  seed-corpus:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' &&
      github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Lua 5.1
        run: sudo apt install -y lua5.1

      - run: make check
